Update scale ci to fix version issues
greenplum-db/gpbackup pull request #719
Opened 2023-09-12 17:04 UTC by AJR-VMware

Move everything for this pipeline to RHEL8-compatible, to deal with GLIBC mismatches.

There's still a bug in the pipeline, but it's related to the changes to directory structure so this should go in to start pinning down some of the moving parts.

2023-09-13 19:22 UTC, khuddlefish requested changes
The artifact you're pointing at is built for the wrong platform still

2023-09-13 19:22 UTC, khuddlefish commented on ci/scale/scale_pipeline.yml
>      regexp: server/published/gpdb6/server-rc-(.*)-rhel7_x86_64.tar.gz
You're still pointing at a rhel7 artifact so this is not `rhel8` like the name says

2023-09-13 21:13 UTC, AJR-VMware commented on ci/scale/scale_pipeline.yml
>      regexp: server/published/gpdb6/server-rc-(.*)-rhel7_x86_64.tar.gz
I had it flown right but must have not committed that change.  Good catch, thank you.

2023-09-14 17:31 UTC, khuddlefish approved these changes

2023-09-15 13:50 UTC, merged